version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.7
    - 4.3.8
    - 5.0.9
    - 5.1.2
    - 5.1.3
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: workbox-build
    versions:
    - 6.0.2
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: fs-extra
    versions:
    - 9.0.1
  - dependency-name: less-loader
    versions:
    - 7.0.2
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.3.3
